### ISSUE TITLE
wps插件如何调用自己的保存方法

### ISSUE THREAD

**Issue by badspider7** [xiaohang2020/wps#1]
你好，想问一下如何通过   _WpsInvoke  调用wps的 保存接口

**Comment by herman-hang** [comment]
可以查询uploadFile关键字即可看到保存相关操作

**Comment by herman-hang** [comment]
> 你好，想问一下如何通过   _WpsInvoke  调用wps的 保存接口

可以查询uploadFile关键字即可看到保存相关操作
